### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by 991rajat** [991rajat/meme-backend#1]
Add a readme

**Comment by aditya28sarin** [comment]
can you assign this issue to me?

**Comment by 991rajat** [comment]
It'a simple task and not related to any competition would you like to do? @aditya28sarin

**Comment by aditya28sarin** [comment]
Yes sure, I want to do it. Could you assign me?

Aditya Sarin

**Comment by aditya28sarin** [comment]
I have created the readme 👍
